---
title: "estimate center and radius"
author: "Take Matsuyama"
date: "2023/03/08"
output: html_document
editor_options: 
   chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  message = FALSE,
  warning = FALSE,
  fig.align = "center",
  out.width='80%',
  out.height='80%'
)
```


```{r library-source}
library(tidyverse)
source("take.R")
library(patchwork)
library(ggforce)
# library(future)
# plan(multisession, workers = parallel::detectCores() - 1) # Use all available cores

```


# Overview

ラベルデータから円の中心座標と半径を見積もる

`process_csv.Rmd` を実行して得られた.Rds ファイルよりデータを読み込みグリッド方を用いて中心の座標と半径を見積もる。

```{r function}
calculate_ratio <- function(x_c, y_c, r, df) {
  dist <- sqrt((df$x - x_c)^2 + (df$y - y_c)^2)
  n_points_inside <- sum(dist < r)
  
  return(n_points_inside / r)
}

iterative_grid_search <- function(df, max_iterations = 10, grid_resolution = c(20, 20, 50), convergence_threshold = 1e-4, history = FALSE) {
  
  x_init <- df$x %>% quantile(c(0.05, 0.95)) %>% mean() + c(-100,100)  
  y_init <- df$y %>% quantile(c(0.05, 0.95)) %>% mean() + c(-100,100)  
  candidate_x_c <- seq(x_init[1], x_init[2], length.out = grid_resolution[1])
  candidate_y_c <- seq(y_init[1], y_init[2], , length.out = grid_resolution[2])
  candidate_r <- seq(200, df$x %>% quantile(c(0.05, 0.95)) %>% diff(), length.out = grid_resolution[3])

  prev_center <- NULL
  prev_radius <- NULL
  iteration <- 1

  # Initialize history lists
  if (history){
    loss_history <- list()
    estimates_history <- list()    
  }

  while (iteration <= max_iterations) {
    candidate_grid <- expand.grid(x_c = candidate_x_c, y_c = candidate_y_c, r = candidate_r)
    candidate_grid$ratio <- purrr::pmap_dbl(candidate_grid, calculate_ratio, df = df)

    max_index <- which.max(candidate_grid$ratio)
    estimated_center <- candidate_grid[max_index, c("x_c", "y_c")]
    estimated_radius <- candidate_grid[max_index, "r"]

    if (history){
      # Store the loss and estimates for this iteration
      loss_history[[iteration]] <- candidate_grid[max_index, "ratio"]
      estimates_history[[iteration]] <- data.frame(
        center_x = estimated_center[1,1], 
        center_y = estimated_center[1,2], 
        radius = estimated_radius
      )      
    }

    # Check convergence
    if (!is.null(prev_center) && !is.null(prev_radius)) {
      center_change <- max(abs(prev_center - estimated_center))
      radius_change <- abs(prev_radius - estimated_radius)

      if (center_change < convergence_threshold && radius_change < convergence_threshold) {
        break
      }
    }

    prev_center <- estimated_center
    prev_radius <- estimated_radius

    # Refine the search grid for the next iteration
    refinement_range <- 25 * (1 - (iteration - 1) / max_iterations)
    candidate_x_c <- seq(
      estimated_center$x_c - refinement_range, 
      estimated_center$x_c + refinement_range, 
      length.out = grid_resolution[1]
    )
    candidate_y_c <- seq(
      estimated_center$y_c - refinement_range, 
      estimated_center$y_c + refinement_range, 
      length.out = grid_resolution[2]
    )
    candidate_r <- seq(
      pmax(0, estimated_radius - refinement_range), 
      estimated_radius + refinement_range, 
      length.out = grid_resolution[3])

    iteration <- iteration + 1
  }

  if (history){
    # Combine the history lists into a single data frame
    # history_df <- purrr::map2_dfr(estimates_history, loss_history, ~mutate(.x, loss = .y))
    history_df <- purrr::imap_dfr(estimates_history, function(est, iter) {
      mutate(est, iteration = iter, loss = loss_history[[iter]])
    })



    return(
      final_estimate = data.frame(
        center_x = estimated_center[1,1], 
        center_y = estimated_center[1,2], 
        radius = estimated_radius, 
        n_iterations = iteration
      )  %>% add_column(history = list(history_df))
    )    
  } else {
    return(
      final_estimate = data.frame(
        center_x = estimated_center[1,1], 
        center_y = estimated_center[1,2], 
        radius = estimated_radius, 
        n_iterations = iteration
      )
    )
  }
}
```


```{r load-data}
df <- readRDS(paste0("df_", split_path(getwd())[1], ".Rds"))
```

```{r estimate-circle}
df_circle <- df %>% 
  group_by(id, bodypart) %>% 
  nest() %>% 
  summarise(
    estimate = map(data, ~iterative_grid_search(., 
      max_iterations = 300, 
      convergence_threshold = 1e-4, 
      grid_resolution = c(6, 6, 6), 
      history = TRUE)
    )
  ) %>% 
  unnest(estimate)

```


```{r plot-circle-and-history, out.width='100%', fig.dim = c(14, 7)}
animals <- df$id %>% unique()
bodyparts <- df$bodypart %>% unique()

for (a in animals){
  for (b in bodyparts){
    df_ab <- df %>% 
      filter(id == a, bodypart == b)

    df_circle_ab <- df_circle %>% 
      filter(id == a, bodypart == b)

    df_circle_history_ab <- df_circle_ab %>% 
      group_by(id, bodypart, history) %>% 
      summarise() %>% unnest(history)

    p_estimate <- ggplot() +
      geom_point(
        aes(x = x, y = y), alpha = 1/10, size = .1,
        data = df_ab
      ) +
      ggforce::geom_circle(
        aes(x0 = center_x, y0 = center_y, r = radius),
        color = "purple",
        data = df_circle_ab
      ) + 
      coord_fixed() +
      theme_minimal()    

    p_history <- df_circle_history_ab %>% 
      filter(iteration > 2) %>% 
      pivot_longer(cols = center_x:radius) %>% 
      ggplot() +
        geom_line(aes(x = iteration, y = value)) +
        facet_wrap(vars(name), scales = "free_y", ncol = 1) +
         theme_minimal() 

    print(
    (p_estimate + p_history) +
        plot_annotation(
          title = paste("Center & radius estimate: id =", a, "| bodypart =", b)
       ) 
    )

  }

}
```


```{r save-data}
df <- df %>% left_join(
  df_circle %>% select(-c(history, n_iterations)), 
  by = c("id", "bodypart")
)

glimpse(df)

split_path <- function(path) {
  if (dirname(path) %in% c(".", path))
   return(basename(path))
  return(c(basename(path), split_path(dirname(path))))
}

saveRDS(df, paste0("df_", split_path(getwd())[1], "_circle.Rds"))
# saveRDS()


```
